---
title: "OVIWC Water Quality DashBoard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(crosstalk)
library(tidyverse)
library(DBI)
library(odbc)
library(lubridate)
library(hms)
library(glue)
library(dbplyr)
library(janitor)
library(plotly)
library(leaflet)
library(DT)
library(htmlwidgets)

WQ <- dbConnect(odbc(), 
                Driver = "SQL Server",
                Server = "localhost\\SQLEXPRESS", 
                Database = "TWQD", 
                Trusted_Connection = "True")

#GW data all

WQ_Result <- tbl(WQ, "Result") %>%
  collect() 

WQ_Activity <- tbl(WQ, "Activity") %>%
  collect()

WQ_All <- inner_join(WQ_Result,WQ_Activity, by = "ActivityIdentifier") %>%
  select(CharacteristicName, ResultMeasureValue, ResultMeasureUnitCode, StartDate.y, StartTime.y, MonitoringLocationIdentifier.y, ProjectIdentifier.y) %>%
  rename(Characteristic = CharacteristicName, Result = ResultMeasureValue, Unit = ResultMeasureUnitCode, Date = StartDate.y, Time = StartTime.y, Site = MonitoringLocationIdentifier.y, Project = ProjectIdentifier.y) 


```

Updated `r format(Sys.time(), '%B %d, %Y')`. Blank results indicate the characteristic was tested but not detected. 

Lone Pine
=======================================================================

Column {data-width=400}
-----------------------------------------------------------------------

### Raw Data, sorted by most recent results

```{r}

LP_data <- WQ_All %>%
  filter(Project == "SWQM-LP") %>%
  select(-Project) %>%
  arrange(desc(Date), Site)

LP_table <- datatable(LP_data, extensions = c("Buttons", "FixedColumns"),
              filter = 'top', 
              options = list (autoWidth = TRUE, 
                              dom = 'blftip',
                              pageLength = 30, 
                              searchHighlight = FALSE,
                              buttons = c('copy','csv','print'),
                              scrollx = TRUE, 
                              fixedColumns = list(leftColumns = 2)), 
              class = c('compact cell-border stripe hover'), 
              rownames = FALSE)

LP_table
```

Column {data-width=400}
-----------------------------------------------------------------------

### Water Temperature

```{r}

LP_data_past_year <- WQ_All %>%
  filter(Project == "SWQM-LP") %>%
  mutate(Date = as.Date(Date)) %>%
  mutate(Result = as.numeric(Result)) %>%
  filter(Date >= (Sys.Date() - years(2)))
  

LP_Water_Temp_Plot <- ggplot(data = filter(LP_data_past_year, Characteristic == "Temperature, water"), aes(x= Date, y = Result, color = Site)) +
  geom_line() +
  labs(title = "", y = "Degrees C")

ggplotly(LP_Water_Temp_Plot)


```

### Specific Conductance

```{r}
LP_Water_SPC_Plot <- ggplot(data = filter(LP_data_past_year, Characteristic == "Specific conductance"), aes(x= Date, y = Result, color = Site)) +
  geom_line() +
  labs(title = "", y = "mS/cm")

ggplotly(LP_Water_SPC_Plot)

```

### Turbidity

```{r}
LP_Water_Turb_Plot <- ggplot(data = filter(LP_data_past_year, Characteristic == "Turbidity"), aes(x= Date, y = Result, color = Site)) +
  geom_line() +
  labs(title = "", y = "FNU")

ggplotly(LP_Water_Turb_Plot)

```

Big Pine
=======================================================================


```{r}
BP_data <- WQ_All %>%
  filter(Project == "GWQM-BP") %>%
  select(-Project) %>%
  arrange(desc(Date), Site)

BP_table <- datatable(BP_data, extensions = c("Buttons", "FixedColumns"),
              filter = 'top', 
              options = list (autoWidth = TRUE, 
                              dom = 'blftip',
                              pageLength = 30, 
                              searchHighlight = FALSE,
                              buttons = c('copy','csv','print'),
                              scrollx = TRUE, 
                              fixedColumns = list(leftColumns = 2)), 
              class = c('compact cell-border stripe hover'), 
              rownames = FALSE)

BP_table
```